### ISSUE TITLE
After install and download of library error

### ISSUE THREAD

**Issue by TheDude005** [lutraconsulting/qgis-crayfish-plugin#195] opened 2016-05-17 02:54 UTC
After downloading the plugin and installing it from the QGIS plugin repository it notified me that crayfish depended on a library to run and that it would try and download and install it for me.  After it downloaded and installed it said it was successful, however after hitting OK it then gave me this traceback

Couldn't load plugin crayfish due to an error when calling its initGui() method 

OSError: libproj.so.0: cannot open shared object file: No such file or directory 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 315, in startPlugin
    plugins[packageName].initGui()
  File "/home/jordan/.qgis2/python/plugins/crayfish/plugin.py", line 73, in initGui
    if not ensure_library_installed():
  File "/home/jordan/.qgis2/python/plugins/crayfish/gui/install_helper.py", line 133, in ensure_library_installed
    load_library()
  File "/home/jordan/.qgis2/python/plugins/crayfish/core.py", line 85, in load_library
    lib = ctypes.cdll.LoadLibrary(libpath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libproj.so.0: cannot open shared object file: No such file or directory

Python version: 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010] 
QGIS version: 2.14.2-Essen Essen, exported 

crayfish 2.2, QGIS 2.14.2-Essen on Linux 4.2.0-35-generic

**Comment by wonder-sk** [comment] 2016-05-17 03:05
Thanks for the report, this is however a duplicate of #187, so I am closing this one...

**Closed by wonder-sk** 2016-05-17 03:05 UTC
