### ISSUE TITLE
 Not possible to remove quantities

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#115] opened 2015-06-08 15:51 UTC
Once a quantity is added to the crayfish layer tree it is not possible to remove it from the tree. The only way is to close the crayfish from the main qgis layer which closes all the quantities.

**Comment by wonder-sk** [comment] 2015-06-08 15:58
Duplicate of #95

**Closed by wonder-sk** 2015-06-08 15:58 UTC
Labels: enhancement
