### ISSUE TITLE
Issue in displaying correct variable and time values in Mesh and Crayfish 

### ISSUE THREAD

**Issue by saeri-ims** [lutraconsulting/qgis-crayfish-plugin#412] opened 2019-11-10 16:22 UTC
Hello,

[Linux Ubuntu 18 OS, QGIS 3.4 LTR.]

I have been dealing with more and more .nc (and .grib) files and I started using MESH in QGIS for their import and visualisation. Additionally, i looked at the crayfish plugin to have the plot and the animation, however so far i have had two main problems. 
1) I cannot display the correct values of the variables i have in the nc file (e.f. sea temperature) See image
![Screenshot from 2019-11-10 16-09-32](https://user-images.githubusercontent.com/42073830/68547049-b47bc780-03bb-11ea-9f2f-d8ea2e15c98c.png)

2) I cannot understand the meaning of datasets in selected groups: i move the slider to browse through time in the dataset but i cannot see the time properly (it is always 12:00:00). I guess i am browsing for sea temp at 10 metre depth at various time periods. But this is hard to tell from the settings.
![Screenshot from 2019-11-10 16-04-22](https://user-images.githubusercontent.com/42073830/68547056-c5c4d400-03bb-11ea-80a6-30d666afaf24.png)

However, when i plot the data using crayfish i get a better idea, although the values on the x and y of the plot are again rather odd. I guess i should not consider the negative and the values > 24. But again, the value of Sea temp are difficult to understand.

![Screenshot from 2019-11-10 15-58-39](https://user-images.githubusercontent.com/42073830/68547144-cb6ee980-03bc-11ea-9e32-1c2f837fec8c.png)

So, how can i display the proper values for the climate variables? and how can I see the time correctly in the settings of the layer properties?

Thanks a lot.

PS note that i have also used the data here http://planet.qgis.org/planet/user/21/ but i get always the two problems.

**Comment by PeterPetrik** [comment] 2020-01-15 07:46
Hi @saeri-ims, first of all, could you please try to load your dataset in QGIS 3.10. There have been a lot of changes in MDAL/QGIS in this area, so your bug is maybe already fixed.

I think this is a duplicate of https://github.com/lutraconsulting/MDAL/issues/107 that was fixed in QGIS 3.6.2

if the problem occurs even with QGIS 3.10, please reopen the issue

**Closed by PeterPetrik** 2020-01-15 07:46 UTC
Labels: bug, feedback

**Comment by saeri-ims** [comment] 2020-01-15 12:14
@PeterPetrik ok i will follow your advise and give it a go on QGIS 3.10 Thanks for pointing to the MDAL post too.
