### ISSUE TITLE
Discrepency between contour export to polygon and polyline

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#419] opened 2020-01-08 16:50 UTC
![image003](https://user-images.githubusercontent.com/2649047/71998142-02377380-3237-11ea-858a-5a0ef740871c.png)

**Comment by PeterPetrik** [comment] 2020-01-14 11:37
![Screenshot 2020-01-14 at 12 36 28](https://user-images.githubusercontent.com/804608/72341430-8459e900-36ca-11ea-8a03-590e688bf7c0.png)

- green -> triangular mesh
- red -> exported contour lines
- blue -> exported countour polygons (graduated renderer)

so the problem is that the polygons match the triangular mesh, but the lines does not.

**Comment by PeterPetrik** [comment] 2020-01-14 11:48
looks like a bug in analysis export contour algorithm. the exported polygons overlap....

**Comment by PeterPetrik** [comment] 2020-01-15 07:37
just a snipped for testing the contour export from python console

```
from qgis.analysis import QgsMeshContours
c = QgsMeshContours(iface.activeLayer())
g = c.exportPolygons(QgsMeshDatasetIndex(1,0), 1.0, 1.2, 0)
r = QgsRubberBand(iface.mapCanvas(), QgsWkbTypes.PolygonGeometry)
r.setWidth(10)
r.setToGeometry(g)
```

**Comment by PeterPetrik** [comment] 2020-01-15 09:26
closing, this is QGIS issue

**Closed by PeterPetrik** 2020-01-15 09:26 UTC
Labels: bug, processing
