### ISSUE TITLE
Support for LISFLOOD model outputs

### ISSUE THREAD

**Issue by EdRollason** [lutraconsulting/qgis-crayfish-plugin#232] opened 2016-09-19 19:38 UTC
It would be great if crayfish could support [LISFLOOD-FP ](http://www.bristol.ac.uk/geography/research/hydrology/models/lisflood/)output files.  These are standard asc grid files.

Manual for the model is here: http://www.bristol.ac.uk/media-library/sites/geography/migrated/documents/lisflood-manual-v5.9.6.pdf 

Attached some example output files of water depth produced by one of the exercises on the website here: http://www.bristol.ac.uk/geography/research/hydrology/models/lisflood/training/
[Results.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/480937/Results.zip)

**Comment by saberraz** [comment] 2016-09-20 08:32
@EdRollason the ascii format is very outdated and not a recommended format to handle temporal data. It is more of a request to the LISFLOOD developer to use a more standard format (e.g. netCDF: see SWW format of AnuGA) or HDF format (e.g. xmdf: TUFLOW).

If they are not willing to change the output format, you can use a python/gdal script as a part of your post processing and convert the ascii files to netCDF. Crayfish can handle nc files.

**Comment by EdRollason** [comment] 2016-09-20 09:46
Hi Sab
Cheers for this.  I'll drop the lisflood guys an email and see what they think.  In the short-term I'll look at converting the asciis over to something else.

Ed

Date: Tue, 20 Sep 2016 01:32:40 -0700

**Comment by saberraz** [comment] 2017-06-09 14:52
@EdRollason this has been implemented in master. Let me know if you want to test it? Please note it is not yet available from the QGIS repo.

**Comment by saberraz** [comment] 2017-06-09 15:09
I close this. Duplicate of #246

**Closed by saberraz** 2017-06-09 15:09 UTC
Labels: formats

**Comment by EdRollason** [comment] 2017-06-09 15:44
Yes I'd be happy to test.

**Comment by PeterPetrik** [comment] 2017-06-10 06:44
@EdRollason sorry for confusion, it is not yet on master. Please follow #246 to keep track of progress on this ticket
