### ISSUE TITLE
Mac osx install issues on installing dependencies

### ISSUE THREAD

**Issue by EdRollason** [lutraconsulting/qgis-crayfish-plugin#234] opened 2016-09-20 13:56 UTC
Trying to run <sudo apt-get install build-essential libqt4-dev qt4-qmake libgdal-dev libhdf5-serial-dev libproj-dev qgis> gives me a command not found error. 

I understand OSX doesn't support apt-get - should this not be a brew install method or similar?

Running OSX El Capitan 10.11.6.

**Comment by saberraz** [comment] 2016-09-20 15:35
@EdRollason unfortunately we had issues with OSX binaries. @PeterPetrik did prepare some binaries for OSX:
http://www.lutraconsulting.co.uk/products/crayfish/viewer/binaries/Darwin64/

But there is an issue with a python module (if I am correct) which crashes the plugin. We might have another attempt for the future release to produce OSX binaries.

In longer term, we'd like to move all the code to python, but it is a huge/time consuming task and well beyond our free time.

**Comment by EdRollason** [comment] 2016-09-21 09:16
@saberraz  - Where does it want that binary to be stored?

**Comment by saberraz** [comment] 2016-09-21 09:45
@EdRollason just checked and it is broken in OSX. You can try yourself:
download and extract the files and place them here:
/Users/YOURUSERNAME/.qgis2/python/plugins/crayfish

You need to install Crayfish first.

**Comment by PeterPetrik** [comment] 2016-09-22 05:37
Hi, this is duplicate of issue #220. Instructions with `brew` are in this section: https://github.com/lutraconsulting/qgis-crayfish-plugin#installing-crayfish-on-mac-os-experimental, however I do not know if resulting binary would work or not.

**Closed** 2016-09-22 05:37 UTC
Labels: duplicate
